# configuration yaml file

# report start/end dates
# emails with dates outside of this range will be excluded
reportStart: "2022-01-01"
reportEnd:   "2023-03-12"

# ip range from which senders will be included, based on the email
# "Received" header.
receivedIPFragment: "10.1.99."

# legitimate senders is a regular expression string
validSenderRegexpStr: "(?i)(this|that|another.com)"

# holidays during which emails are ignored
holidayStrings: 
  -
    start: "2022-02-20"
    end: "2022-02-22"
  -
    start: "2022-02-25"
    end: "2022-02-27"
